// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StyleHub.DataAccess;

#nullable disable

namespace StyleHub.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250118071306_RemoveIsDefaultColumnFromTranslationTables")]
    partial class RemoveIsDefaultColumnFromTranslationTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("StyleHub.Models.AdImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdvertisementId")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdvertisementId");

                    b.ToTable("AdImages");
                });

            modelBuilder.Entity("StyleHub.Models.AdTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdvertisementId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdvertisementId");

                    b.ToTable("AdTranslations");
                });

            modelBuilder.Entity("StyleHub.Models.Advertisement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Advertisements");
                });

            modelBuilder.Entity("StyleHub.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "images\\categories\\defence_industries.jpg"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "images\\categories\\civil_industries.jpg"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "images\\categories\\medical_equipment.jpg"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "images\\categories\\sports_equipment.jpg"
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "images\\categories\\physical_therapy_devices.jpg",
                            ParentCategoryId = 4
                        });
                });

            modelBuilder.Entity("StyleHub.Models.CategoryTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("CategoryTranslaltiosns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Industries related to defense and military.",
                            Language = "en-us",
                            Name = "Defence Industries"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "صناعات متعلقة بالدفاع والعسكرية.",
                            Language = "ar-eg",
                            Name = "الصناعات الدفاعية"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Industries for civilian applications.",
                            Language = "en-us",
                            Name = "Civil Industries"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "صناعات للاستخدامات المدنية.",
                            Language = "ar-eg",
                            Name = "الصناعات المدنية"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "Equipment used in healthcare and medical fields.",
                            Language = "en-us",
                            Name = "Medical Equipment"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "المعدات المستخدمة في مجالات الرعاية الصحية والطبية.",
                            Language = "ar-eg",
                            Name = "المعدات الطبية"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Description = "Equipment for sports and fitness.",
                            Language = "en-us",
                            Name = "Sports Equipment"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Description = "معدات الرياضة واللياقة البدنية.",
                            Language = "ar-eg",
                            Name = "معدات رياضية"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            Description = "Devices designed for physical therapy and rehabilitation.",
                            Language = "en-us",
                            Name = "Physical Therapy Devices"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            Description = "أجهزة مصممة للعلاج الطبيعي وإعادة التأهيل.",
                            Language = "ar-eg",
                            Name = "أجهزة العلاج الطبيعي"
                        });
                });

            modelBuilder.Entity("StyleHub.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 4
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 5
                        });
                });

            modelBuilder.Entity("StyleHub.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("StyleHub.Models.ProductTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductTranslations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "General Purpose: Intended for bombing from adequate aircraft of NATO and Russian standards and from the plane of light aviation under specific conditions.",
                            Language = "en-US",
                            Name = "HAFEZ FAMILY",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "مصممة للقصف من طائرات الناتو وروسيا أو الطائرات الخفيفة في ظل ظروف معينة.",
                            Language = "ar-eg",
                            Name = "عائلة حافظ",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "A solid-state fuse with a powerful microcontroller for air-to-surface aerial bombs.",
                            Language = "en-US",
                            Name = "HAFEZ 4 (AIR TO SURFACE FUZES)",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "صمام صلب مع متحكم دقيق قوي للقنابل الجوية جو-أرض.",
                            Language = "ar-eg",
                            Name = "حافظ 4 (طابة جو/أرض)",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 5,
                            Description = "Ensures a reliable power supply for trains, meeting high safety and quality standards in the railway industry.",
                            Language = "en-US",
                            Name = "Power Coaches",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 6,
                            Description = "توفر إمدادًا موثوقًا بالطاقة للقطارات مع الالتزام بأعلى معايير السلامة والجودة في صناعة السكك الحديدية.",
                            Language = "ar-eg",
                            Name = "عربات الطاقة",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 7,
                            Description = "Ideal for safe and efficient transportation of liquids, constructed with stainless steel for high cleanliness.",
                            Language = "en-US",
                            Name = "Tank Wagon",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 8,
                            Description = "مثالية لنقل السوائل بأمان وكفاءة، مصنوعة من الفولاذ المقاوم للصدأ لضمان نظافة عالية.",
                            Language = "ar-eg",
                            Name = "عربة خزان",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 9,
                            Description = "Compliant with Egyptian and European safety standards for baby incubators.",
                            Language = "en-US",
                            Name = "Infant Incubator",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 10,
                            Description = "متوافقة مع المواصفات المصرية والأوروبية لأجهزة حاضنات الأطفال.",
                            Language = "ar-eg",
                            Name = "حاضنة أطفال",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 11,
                            Description = "Designed for upper limb training of wheelchair users, with customizable settings and performance tracking.",
                            Language = "en-US",
                            Name = "Multifunctional Training Device",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 12,
                            Description = "مصمم لتدريب الأطراف العلوية لمستخدمي الكراسي المتحركة مع إعدادات قابلة للتخصيص ومتابعة الأداء.",
                            Language = "ar-eg",
                            Name = "جهاز تدريب متعدد الوظائف",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 13,
                            Description = "Devices designed for physical therapy and rehabilitation.",
                            Language = "en-US",
                            Name = "Physical Therapy Devices",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 14,
                            Description = "أجهزة مصممة للعلاج الطبيعي وإعادة التأهيل.",
                            Language = "ar-eg",
                            Name = "أجهزة العلاج الطبيعي",
                            ProductId = 7
                        });
                });

            modelBuilder.Entity("StyleHub.Models.AppUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.HasDiscriminator().HasValue("AppUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StyleHub.Models.AdImage", b =>
                {
                    b.HasOne("StyleHub.Models.Advertisement", "Advertisement")
                        .WithMany("Images")
                        .HasForeignKey("AdvertisementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advertisement");
                });

            modelBuilder.Entity("StyleHub.Models.AdTranslation", b =>
                {
                    b.HasOne("StyleHub.Models.Advertisement", "Advertisement")
                        .WithMany("Translations")
                        .HasForeignKey("AdvertisementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advertisement");
                });

            modelBuilder.Entity("StyleHub.Models.Category", b =>
                {
                    b.HasOne("StyleHub.Models.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("StyleHub.Models.CategoryTranslation", b =>
                {
                    b.HasOne("StyleHub.Models.Category", "Category")
                        .WithMany("CategoryTranslations")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("StyleHub.Models.Product", b =>
                {
                    b.HasOne("StyleHub.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("StyleHub.Models.ProductImage", b =>
                {
                    b.HasOne("StyleHub.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StyleHub.Models.ProductTranslation", b =>
                {
                    b.HasOne("StyleHub.Models.Product", "Product")
                        .WithMany("ProductTranslations")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StyleHub.Models.Advertisement", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("StyleHub.Models.Category", b =>
                {
                    b.Navigation("CategoryTranslations");

                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("StyleHub.Models.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("ProductTranslations");
                });
#pragma warning restore 612, 618
        }
    }
}
