//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StyleHubWeb.Resources.Areas.Customer.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BoardOfDirectors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BoardOfDirectors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StyleHubWeb.Resources.Areas.Customer.Views.Home.BoardOfDirectors", typeof(BoardOfDirectors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AbdelNasser {
            get {
                return ResourceManager.GetString("AbdelNasser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AbdullahAl_Alabi {
            get {
                return ResourceManager.GetString("AbdullahAl-Alabi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Abu_El_Naga {
            get {
                return ResourceManager.GetString("Abu El-Naga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Adel_Abdel_Gawad {
            get {
                return ResourceManager.GetString("Adel Abdel-Gawad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Advisor {
            get {
                return ResourceManager.GetString("Advisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Ahmed_El_Boulaky {
            get {
                return ResourceManager.GetString("Ahmed El-Boulaky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Ahmed_M__Eid {
            get {
                return ResourceManager.GetString("Ahmed M. Eid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Ahmed_Othman {
            get {
                return ResourceManager.GetString("Ahmed Othman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AhmedMostafaEl_Adly {
            get {
                return ResourceManager.GetString("AhmedMostafaEl-Adly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Amr_Hossam_ {
            get {
                return ResourceManager.GetString("Amr Hossam.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amr Riyad Mohamed El-Mahdy.
        /// </summary>
        internal static string AmrEl_Mahdy {
            get {
                return ResourceManager.GetString("AmrEl-Mahdy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Appointment {
            get {
                return ResourceManager.GetString("Appointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Appointment2 {
            get {
                return ResourceManager.GetString("Appointment2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Appointment3 {
            get {
                return ResourceManager.GetString("Appointment3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Ashraf_Nabil {
            get {
                return ResourceManager.GetString("Ashraf Nabil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Asmaa_Rizk_Khafaga {
            get {
                return ResourceManager.GetString("Asmaa Rizk Khafaga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Board_Member___CEO {
            get {
                return ResourceManager.GetString("Board Member & CEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoardOfDirectorsContent.
        /// </summary>
        internal static string BoardOfDirectorsContent {
            get {
                return ResourceManager.GetString("BoardOfDirectorsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BoardOfDirectorsContentNew {
            get {
                return ResourceManager.GetString("BoardOfDirectorsContentNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoardOfDirectorsDescription.
        /// </summary>
        internal static string BoardOfDirectorsDescription1 {
            get {
                return ResourceManager.GetString("BoardOfDirectorsDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoardOfDirectorsDescription.
        /// </summary>
        internal static string BoardOfDirectorsDescription2 {
            get {
                return ResourceManager.GetString("BoardOfDirectorsDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoardOfDirectors.
        /// </summary>
        internal static string BoardOfDirectorsTitle {
            get {
                return ResourceManager.GetString("BoardOfDirectorsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building a Strong Reputation.
        /// </summary>
        internal static string BuildingStrongReputation {
            get {
                return ResourceManager.GetString("BuildingStrongReputation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuildingStrongReputationContent.
        /// </summary>
        internal static string BuildingStrongReputationContent {
            get {
                return ResourceManager.GetString("BuildingStrongReputationContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEO of the company.
        /// </summary>
        internal static string CEOCompany {
            get {
                return ResourceManager.GetString("CEOCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chairman of the Board.
        /// </summary>
        internal static string Chairman {
            get {
                return ResourceManager.GetString("Chairman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Chairman2 {
            get {
                return ResourceManager.GetString("Chairman2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Chief_Executive_Officer {
            get {
                return ResourceManager.GetString("Chief Executive Officer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChiefExecutiveOfficer {
            get {
                return ResourceManager.GetString("ChiefExecutiveOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Policy.
        /// </summary>
        internal static string CompanyPolicy {
            get {
                return ResourceManager.GetString("CompanyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyPolicyContent.
        /// </summary>
        internal static string CompanyPolicyContent {
            get {
                return ResourceManager.GetString("CompanyPolicyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Posts.
        /// </summary>
        internal static string CompanyPosts {
            get {
                return ResourceManager.GetString("CompanyPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyPostsContent.
        /// </summary>
        internal static string CompanyPostsContent {
            get {
                return ResourceManager.GetString("CompanyPostsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Vision.
        /// </summary>
        internal static string CompanyVision {
            get {
                return ResourceManager.GetString("CompanyVision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyVisionContent.
        /// </summary>
        internal static string CompanyVisionContent {
            get {
                return ResourceManager.GetString("CompanyVisionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Contracting {
            get {
                return ResourceManager.GetString("Contracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Satisfaction.
        /// </summary>
        internal static string CustomerSatisfaction {
            get {
                return ResourceManager.GetString("CustomerSatisfaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerSatisfactionContent.
        /// </summary>
        internal static string CustomerSatisfactionContent {
            get {
                return ResourceManager.GetString("CustomerSatisfactionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Deputy_Financial {
            get {
                return ResourceManager.GetString("Deputy Financial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development.
        /// </summary>
        internal static string Development {
            get {
                return ResourceManager.GetString("Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DevelopmentContent.
        /// </summary>
        internal static string DevelopmentContent {
            get {
                return ResourceManager.GetString("DevelopmentContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DirectorGeneral {
            get {
                return ResourceManager.GetString("DirectorGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DirectoroftheCentral {
            get {
                return ResourceManager.GetString("DirectoroftheCentral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EmadEl_Din {
            get {
                return ResourceManager.GetString("EmadEl-Din", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Eman_Mohamed_Ragab {
            get {
                return ResourceManager.GetString("Eman Mohamed Ragab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expansion.
        /// </summary>
        internal static string Expansion {
            get {
                return ResourceManager.GetString("Expansion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpansionContent1.
        /// </summary>
        internal static string ExpansionContent1 {
            get {
                return ResourceManager.GetString("ExpansionContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpansionContent2.
        /// </summary>
        internal static string ExpansionContent2 {
            get {
                return ResourceManager.GetString("ExpansionContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EyadHussein {
            get {
                return ResourceManager.GetString("EyadHussein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Financial {
            get {
                return ResourceManager.GetString("Financial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FinancialAdvisor {
            get {
                return ResourceManager.GetString("FinancialAdvisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growth.
        /// </summary>
        internal static string Growth {
            get {
                return ResourceManager.GetString("Growth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GrowthContent.
        /// </summary>
        internal static string GrowthContent {
            get {
                return ResourceManager.GetString("GrowthContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Hossam_Ali {
            get {
                return ResourceManager.GetString("Hossam Ali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improvement.
        /// </summary>
        internal static string Improvement {
            get {
                return ResourceManager.GetString("Improvement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImprovementContent.
        /// </summary>
        internal static string ImprovementContent {
            get {
                return ResourceManager.GetString("ImprovementContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innovation.
        /// </summary>
        internal static string Innovation {
            get {
                return ResourceManager.GetString("Innovation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InnovationContent.
        /// </summary>
        internal static string InnovationContent {
            get {
                return ResourceManager.GetString("InnovationContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string KarimAdel {
            get {
                return ResourceManager.GetString("KarimAdel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyTasks.
        /// </summary>
        internal static string KeyTasks {
            get {
                return ResourceManager.GetString("KeyTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Legal_ {
            get {
                return ResourceManager.GetString("Legal ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LegalAffairsSector {
            get {
                return ResourceManager.GetString("LegalAffairsSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LegalSector {
            get {
                return ResourceManager.GetString("LegalSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MajorGeneralMohamedIsmail {
            get {
                return ResourceManager.GetString("MajorGeneralMohamedIsmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Managing_Director {
            get {
                return ResourceManager.GetString("Managing Director", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Managing_Director1 {
            get {
                return ResourceManager.GetString("Managing Director1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        internal static string Member {
            get {
                return ResourceManager.GetString("Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MemberoftheCentral {
            get {
                return ResourceManager.GetString("MemberoftheCentral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Military {
            get {
                return ResourceManager.GetString("Military", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Military_Sector {
            get {
                return ResourceManager.GetString("Military Sector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mohamed Al-Dramelly.
        /// </summary>
        internal static string MohamedAl_Dramelly {
            get {
                return ResourceManager.GetString("MohamedAl-Dramelly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MohamedAl_Dramelly2 {
            get {
                return ResourceManager.GetString("MohamedAl-Dramelly2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MohamedSaad {
            get {
                return ResourceManager.GetString("MohamedSaad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mohsen Hassan Morsi Mustafa.
        /// </summary>
        internal static string MohsenHassan {
            get {
                return ResourceManager.GetString("MohsenHassan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Ms_Nouran {
            get {
                return ResourceManager.GetString("Ms.Nouran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Ms_Sama {
            get {
                return ResourceManager.GetString("Ms.Sama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Office_Manager {
            get {
                return ResourceManager.GetString("Office Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Osama_Shehata {
            get {
                return ResourceManager.GetString("Osama Shehata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Public_Relations {
            get {
                return ResourceManager.GetString("Public Relations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        internal static string Quality {
            get {
                return ResourceManager.GetString("Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QualityContent.
        /// </summary>
        internal static string QualityContent {
            get {
                return ResourceManager.GetString("QualityContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Resolutions {
            get {
                return ResourceManager.GetString("Resolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sustainability.
        /// </summary>
        internal static string Sustainability {
            get {
                return ResourceManager.GetString("Sustainability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SustainabilityContent.
        /// </summary>
        internal static string SustainabilityContent {
            get {
                return ResourceManager.GetString("SustainabilityContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Tarek_Abdel_Meguid {
            get {
                return ResourceManager.GetString("Tarek Abdel-Meguid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Technical_and_IT {
            get {
                return ResourceManager.GetString("Technical and IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TechnicalOffice {
            get {
                return ResourceManager.GetString("TechnicalOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training and Development.
        /// </summary>
        internal static string Training_Development {
            get {
                return ResourceManager.GetString("Training&Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training&amp;DevelopmentContent.
        /// </summary>
        internal static string Training_DevelopmentContent {
            get {
                return ResourceManager.GetString("Training&DevelopmentContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ZiadAhmed {
            get {
                return ResourceManager.GetString("ZiadAhmed", resourceCulture);
            }
        }
    }
}
